---
- group:
    name: petclinic

- user:
    name: petclinic
    group: petclinic

- name: put git repo in place
  git:
    repo: https://github.com/secretescapes/grails-petclinic
    dest: /opt/petclinic
    version: fd16b6687437f52e390a6faec82cc94f981b7565 

- name: systemd petclinic
  copy:
    src: petclinic.service
    dest: /etc/systemd/system/petclinic.service
    owner: petclinic
    group: petclinic
    mode: 0644
  notify: petclinic
